

/*
Purpose: AUDIT TRAIL OF CHANGES MADE TO ORDERS
         BULK UPSERT INTO ORDERS FROM A SOURCE STAGING TABLE WHICH CAN BE EITHER EXTERNAL DATA SET LIKE CSV,TXT,EXCEL.
*/

CREATE PROCEDURE DBO.usp_bulkupsertOrders
AS
BEGIN

MERGE DBO.ORDERS T
USING SOURCE_STAGING_TABLE S ON T.ORDER_ID = S.ORDER_ID

WHEN MATCHED THEN
UPDATE SET CUSTOMERID   = S.CUSTOMERID
		   ,ORDERDATE   = S.ORDERDATE
		   ,ADDRESSID   = S.ADDRESSID
		   ,CREATED_AT  = S.CREATED_AT
		   ,MODIFIED_AT = GETDATE()

WHEN NOT MATCHED BY TARGET
THEN
INSERT (
		   ORDER_ID 
		  ,CUSTOMERID 
		  ,ORDERDATE 
		  ,ADDRESSID 
		  ,CREATED_AT 
		  ,MODIFIED_AT
	   )
VALUES (
		 S.ORDER_ID
		,S.CUSTOMERID 
		,S.ORDERDATE 
		,S.ADDRESSID 
		,GETDATE() 
		,GETDATE()
		)

OUTPUT COALESCE(DELETED.ORDER_ID,INSERTED.ORDER_ID)
      ,COALESCE(DELETED.CUSTOMERID,INSERTED.CUSTOMERID)
	  ,COALESCE(DELETED.ORDERDATE,INSERTED.ORDERDATE
	  ,COALESCE(DELETED.ADDRESSID,INSERTED.ADDRESSID
	  ,COALESCE(DELETED.CREATED_AT,INSERTED.CREATED_AT
	  ,COALESCE(DELETED.MODIFIED_AT,INSERTED.MODIFIED_AT)
	  ,$action
	  ,GETDATE()
	  ,SUSER_NAME()
INTO DBO.ORDERS_LOG
    (ORDER_ID  
     ,CUSTOMERID  
     ,ORDERDATE 
     ,ADDRESSID  
     ,CREATED_AT 
     ,MODIFIED_AT 
     ,OPERATION 
     ,UPDATED_ON 
     ,UPDATED_BY
	 );


END