DROP TABLE IF EXISTS DBO.PRODUCT
CREATE TABLE DBO.PRODUCT
(
	PRODUCTID    INT PRIMARY KEY
   ,PRODUCTNAME  NVARCHAR(100)
   ,[WEIGHT]     FLOAT
   ,HEIGHT       FLOAT
   ,PRODUCTIMAGE VARBINARY(MAX)
   ,BARCODE      VARBINARY(MAX)
   ,SKU          INT
   ,QTY_INSTOCK  INT
   ,PRICE        FLOAT UNIQUE
)

GO

DROP TABLE IF EXISTS DBO.USER_ROLES
CREATE TABLE DBO.USER_ROLES
(
	USERROLEID       INT PRIMARY KEY
   ,ROLE_DESCRIPTION VARCHAR(15)
)
GO

DROP TABLE IF EXISTS DBO.CUSTOMER
CREATE TABLE DBO.CUSTOMER
(
	 CUSTOMERID   INT PRIMARY KEY
	,USERNAME     VARCHAR(15)
	,[PASSWORD]   NVARCHAR(15)
	,TITLE        VARCHAR(5)
	,FIRSTNAME    NVARCHAR(25)
	,MIDDLENAME   NVARCHAR(25)
	,LASTNAME     NVARCHAR(25)
	,USERROLEID   INT FOREIGN KEY REFERENCES DBO.USER_ROLES(USERROLEID)
	,CREATED_AT   DATETIME
	,MODIFIED_AT  DATETIME
)
GO

DROP TABLE IF EXISTS DBO.CUSTOMER_ADDRESS
CREATE TABLE DBO.CUSTOMER_ADDRESS
(
	ADDRESSID INT PRIMARY KEY
   ,CUSTOMERID INT FOREIGN KEY REFERENCES DBO.CUSTOMER(CUSTOMERID)
   ,ADDRESS_LINE1 NVARCHAR(25)
   ,ADDRESS_LINE2 NVARCHAR(25)
   ,CITY VARCHAR(15)
   ,[STATE] VARCHAR(25)
   ,PINCODE INT
   ,COUNTRY NVARCHAR(10)
   ,TELEPHONE NVARCHAR(12)
)

GO

DROP TABLE IF EXISTS DBO.ORDERSTATUS
CREATE TABLE DBO.ORDERSTATUS
(
	ORDERSTATUSID INT PRIMARY KEY
   ,STATUS_DESC NVARCHAR(15)
)
GO

DROP TABLE IF EXISTS DBO.ORDERS
CREATE TABLE DBO.ORDERS
(
	ORDER_ID INT PRIMARY KEY
   ,CUSTOMERID INT FOREIGN KEY REFERENCES DBO.CUSTOMER(CUSTOMERID)
   ,ORDERDATE DATETIME
   ,ADDRESSID INT FOREIGN KEY REFERENCES DBO.CUSTOMER_ADDRESS(ADDRESSID)
   ,CREATED_AT DATETIME
   ,MODIFIED_AT DATETIME
)
GO

DROP TABLE IF EXISTS DBO.ORDER_ITEMS
CREATE TABLE DBO.ORDER_ITEMS
(
	ITEM_ID INT PRIMARY KEY
   ,ORDER_ID INT FOREIGN KEY REFERENCES DBO.ORDERS(ORDER_ID)
   ,PRICE FLOAT FOREIGN KEY REFERENCES DBO.PRODUCT(PRICE)
   ,QUANTITY INT
   ,ORDERSTATUSID INT FOREIGN KEY REFERENCES DBO.ORDERSTATUS
)

DROP TABLE IF EXISTS DBO.PRODUCT_LOG
CREATE TABLE DBO.PRODUCT_LOG
(
	ID INT IDENTITY(1,1) NOT NULL
   ,PRODUCTID    INT 
   ,PRODUCTNAME  NVARCHAR(100)
   ,[WEIGHT]     FLOAT
   ,HEIGHT       FLOAT
   ,PRODUCTIMAGE VARBINARY(MAX)
   ,BARCODE      VARBINARY(MAX)
   ,SKU          INT
   ,QTY_INSTOCK  INT
   ,PRICE        FLOAT
   ,OPERATION NVARCHAR(15)
   ,UPDATED_ON DATETIME
   ,UPDATED_BY NVARCHAR(25)
)

DROP TABLE IF EXISTS DBO.CUSTOMER_LOG
CREATE TABLE DBO.CUSTOMER_LOG
(
	 ID INT IDENTITY(1,1) NOT NULL
	,CUSTOMERID   INT
	,USERNAME     VARCHAR(15)
	,[PASSWORD]   NVARCHAR(15)
	,TITLE        VARCHAR(5)
	,FIRSTNAME    NVARCHAR(25)
	,MIDDLENAME   NVARCHAR(25)
	,LASTNAME     NVARCHAR(25)
	,USERROLEID   INT
	,CREATED_AT   DATETIME
	,MODIFIED_AT  DATETIME
	,OPERATION NVARCHAR(15)
    ,UPDATED_ON DATETIME
    ,UPDATED_BY NVARCHAR(25)
)
GO

DROP TABLE IF EXISTS DBO.ORDERS_LOG
CREATE TABLE DBO.ORDERS_LOG
(
	ID INT IDENTITY(1,1) NOT NULL
   ,ORDER_ID INT 
   ,CUSTOMERID INT 
   ,ORDERDATE DATETIME
   ,ADDRESSID INT 
   ,CREATED_AT DATETIME
   ,MODIFIED_AT DATETIME
   ,OPERATION NVARCHAR(15)
   ,UPDATED_ON DATETIME
   ,UPDATED_BY NVARCHAR(25)
)
GO





